const $=(s,e=document)=>e.querySelector(s), $$=(s,e=document)=>[...e.querySelectorAll(s)];
const DBKEY='cwsc_alpha_db', SESSION='cwsc_session';
const fresh=()=>({users:[{id:'u1',username:'GörnaldoBerlin',password:'admin123',email:'owner@cwsc.local',role:'Owner',level:12,xp:2450,credits:12500,gems:350,energy:8,wins:28,losses:11,joined:'17.07.2026'},{id:'u2',username:'TestUser',password:'test123',email:'test@cwsc.local',role:'User',level:7,xp:1420,credits:4800,gems:90,energy:10,wins:12,losses:9,joined:'17.07.2026'}],cards:CW_DATA.cards.slice(0,18).map((c,i)=>({...c,uid:`uc${i}`,favorite:i<2})),deck:[],settings:{animations:true,effects:true,sound:true,music:true,tips:true,private:false,dark:true,muted:false,autoDeck:false,fontSize:100,uiScale:100,volume:70,matchSpeed:'Normal',language:'Deutsch'},suggestions:[{type:'Event',text:'Ein Neon-Tag-Team-Event mit Fraktionsbonus.',status:'eingereicht'}],logs:[],notifications:[['Dein Gratispack ist verfügbar.','vor 2 Min.'],['Night of Champions wurde gestartet.','vor 1 Std.'],['Deine Fusion ist abgeschlossen.','gestern'],['Du hast eine tägliche Mission beendet.','gestern'],['Neue Kartenserie: Arena Zero.','vor 2 Tagen']].map((x,i)=>({title:x[0],date:x[1],read:i>1})),messages:[{from:'Systemnachricht',subject:'Willkommen in der GCWF',text:'Dein Profil wurde erfolgreich für die neue Saison aktiviert.',date:'Heute',read:false},{from:'Admin-Team',subject:'UI Prototype Feedback',text:'Teile uns deine Eindrücke über den Vorschlagsbereich mit.',date:'Gestern',read:false},{from:'Event-Team',subject:'Night of Champions',text:'Das neue Event läuft noch 3 Tage und 14 Stunden.',date:'15.07.',read:true}],draft:Array(25).fill(false),picks:4,missions:CW_DATA.missions.map((x,i)=>({name:x,done:i===5,progress:i===5?1:0,target:i===4?10:3})),gameName:'Comic Wrestling SuperCards',version:'0.1 UI Prototype'});
let db=JSON.parse(localStorage.getItem(DBKEY)||'null')||fresh(), user=null, page='home', authMode='login', adminTab='dashboard', matchState={round:0,own:0,enemy:0};
if(!db.notifications){const migrated=fresh();db.notifications=migrated.notifications;db.messages=migrated.messages;db.version='0.1 UI Prototype';const owner=db.users.find(x=>x.username==='GörnaldoBerlin');if(owner)owner.password='admin123';if(!db.users.some(x=>x.username==='TestUser'))db.users.push(migrated.users[1]);saveSoon()}
function saveSoon(){localStorage.setItem(DBKEY,JSON.stringify(db))}
const save=()=>localStorage.setItem(DBKEY,JSON.stringify(db));
const toast=m=>{const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)};
const rarity=c=>CW_DATA.rarities[c.rarity], ovr=c=>Math.round(Object.values(c.stats).reduce((a,b)=>a+b,0)/5);
function cardHTML(c,selectable=false){const r=rarity(c),initials=c.name.split(' ').map(x=>x[0]).join('').slice(0,2);return `<article class="game-card ${selectable?'selectable':''}" data-card="${c.uid||c.id}" style="--rare:${r[1]}"><div class="fighter">${initials}</div><small>${r[0]} · OVR ${ovr(c)}</small><h3>${c.name}</h3><div class="stats">${[['ST',c.stats.power],['GE',c.stats.speed],['TE',c.stats.technique],['AU',c.stats.stamina],['CH',c.stats.charisma]].map(x=>`<span>${x[0]}<b>${x[1]}</b></span>`).join('')}</div></article>`}
function head(title,sub,action=''){return `<div class="page-head"><div><p class="eyebrow">GCWF COMMAND CENTER</p><h1>${title}</h1><p>${sub}</p></div>${action}</div>`}
function boot(){const particles=$('#particles');for(let i=0;i<34;i++){const p=document.createElement('i');p.className='particle';p.style.left=Math.random()*100+'%';p.style.setProperty('--particle-speed',(4+Math.random()*7)+'s');p.style.setProperty('--particle-delay',(-Math.random()*8)+'s');p.style.setProperty('--particle-color',i%3===0?'#ff3e91':i%3===1?'#54dfff':'#d5a4ff');particles.append(p)}let n=0;const timer=setInterval(()=>{n+=Math.ceil(Math.random()*8);if(n>=100){n=100;clearInterval(timer);$('#startBtn').classList.remove('hidden')}$('#loadPct').textContent=n+'%';$('#loadBar').style.width=n+'%'},70);$('#startBtn').onclick=()=>{user=db.users.find(x=>x.id===localStorage.getItem(SESSION));$('#splash').classList.add('is-leaving');setTimeout(()=>{$('#splash').classList.add('hidden');if(user)openApp();else{$('#auth').classList.add('auth-enter');$('#auth').classList.remove('hidden')}},matchMedia('(prefers-reduced-motion: reduce)').matches?220:720)}}
$('#authSwitch').onclick=()=>{authMode=authMode==='login'?'register':'login';$('#authTitle').textContent=authMode==='login'?'Willkommen zurück':'Betritt die Liga';$('#authSub').textContent=authMode==='login'?'Melde dich an und führe dein Deck zum Ruhm.':'Erstelle deinen persönlichen Ringnamen.';$('#emailLabel').classList.toggle('hidden',authMode==='login')};
$('#authPass').parentElement.insertAdjacentHTML('afterend','<div class="setting-row"><label><input id="showPass" type="checkbox"> Passwort anzeigen</label><label><input id="rememberMe" type="checkbox" checked> Angemeldet bleiben</label></div>');$('#authSwitch').insertAdjacentHTML('afterend','<button id="forgotPass" class="text-btn">Passwort vergessen?</button>');$('#showPass').onchange=e=>$('#authPass').type=e.target.checked?'text':'password';$('#forgotPass').onclick=()=>{$('#authError').textContent='Demo-Hinweis: Owner admin123 · TestUser test123'};
$('#demoBtn').onclick=()=>{user=db.users[0];localStorage.setItem(SESSION,user.id);openApp()};
$('#authForm').onsubmit=e=>{e.preventDefault();const name=$('#authUser').value.trim(),pass=$('#authPass').value;if(authMode==='login'){user=db.users.find(x=>x.username.toLowerCase()===name.toLowerCase()&&x.password===pass);if(!user){$('#authError').textContent='Benutzername oder Passwort ist falsch.';return}}else{if(db.users.some(x=>x.username.toLowerCase()===name.toLowerCase())){$('#authError').textContent='Dieser Benutzername ist bereits vergeben.';return}user={id:'u'+Date.now(),username:name,password:pass,email:$('#authEmail').value,role:'Benutzer',level:1,xp:0,credits:2500,gems:50,energy:10,wins:0,losses:0,joined:new Date().toLocaleDateString('de-DE')};db.users.push(user);db.cards=CW_DATA.cards.slice(0,8).map((c,i)=>({...c,uid:'u'+Date.now()+i}));save()}localStorage.setItem(SESSION,user.id);openApp()};
function openApp(){$('#auth').classList.add('hidden');$('#app').classList.remove('hidden');$('#topName').textContent=$('#sideName').textContent=user.username;$('#sideRole').textContent=$('#topRole').textContent=user.role.toUpperCase();$('#topAvatar').textContent=user.username[0];$('#topLevel').textContent=user.level;$('#credits').textContent=user.credits.toLocaleString('de');$('#gems').textContent=user.gems;$('#energy').textContent=user.energy+'/10';$('.admin-only').classList.toggle('hidden',!['Owner','Administrator'].includes(user.role));const nav=CW_DATA.nav.map(n=>`<button data-page="${n[0]}"><i>${n[2]}</i><span>${n[1]}</span></button>`).join('');$('#sideNav').innerHTML=nav;bindNav();render()}
function bindNav(){$$('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;render()})}
function render(){if(page==='admin'&&!['Owner','Administrator'].includes(user.role)){toast('Du besitzt keine Berechtigung für diesen Bereich.');page='home'}$$('#sideNav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));const label=CW_DATA.nav.find(n=>n[0]===page)?.[1]||'Vorschau';$('#pageTitle').textContent=label;const fn=pages[page]||pages.dev;$('#content').innerHTML=fn();bindPage();scrollTo(0,0)}
const pages={
home:()=>`${head(`Willkommen zurück, ${user.username}`,'Bereit für dein nächstes Match?')}<section class="hero"><div><p class="eyebrow">SAISON 01 · GENESIS</p><h2>NEON<br><em>UPRISING</em></h2><p>Level ${user.level} · Gold-Liga · Siegesserie 4 · Beste Karte OVR ${Math.max(...db.cards.map(ovr))}</p><button class="primary" data-page="play">JETZT ANTRETEN</button></div></section><div class="quick-grid">${[['play','⚔','Spielen','Lokales Match gegen die KI'],['cards','▣','Meine Karten',db.cards.length+' Karten gesammelt'],['packs','◆','Packs öffnen','Gratispack verfügbar'],['fusion','◎','Fusion','Karten verschmelzen'],['deck','▤','Deck bearbeiten','Stärkstes Team aufstellen'],['missions','✓','Missionen','Belohnungen warten']].map(x=>`<button class="tile" data-page="${x[0]}"><i>${x[1]}</i><b>${x[2]}</b><span>${x[3]}</span></button>`).join('')}</div><div class="stats-grid"><div class="stat"><strong>00:00</strong><span>GRATISPACK BEREIT</span><button class="text-btn" data-page="packs">Pack öffnen</button></div><div class="stat"><strong>3T 14H</strong><span>NIGHT OF CHAMPIONS</span><div class="progress"><i style="width:46%"></i></div></div><div class="stat"><strong>2/3</strong><span>TÄGLICHE MISSIONEN</span></div><div class="stat"><strong>${db.cards.length}/75</strong><span>SAMMLUNG</span></div></div><div class="panel"><h3>NEUESTE KARTEN</h3><div class="card-grid">${db.cards.slice(-5).map(cardHTML).join('')}</div></div>`,
cards:()=>`${head('Meine Karten','Durchsuche, sortiere und verwalte deine Sammlung.')}<div class="toolbar"><input class="field" id="cardSearch" placeholder="Karte suchen …"><select class="field" id="rarityFilter"><option value="">Alle Seltenheiten</option>${CW_DATA.rarities.map((r,i)=>`<option value="${i}">${r[0]}</option>`).join('')}</select><select class="field" id="cardSort"><option value="ovr">Stärkste zuerst</option><option value="name">Name</option><option value="level">Level</option></select></div><div id="collection" class="card-grid">${[...db.cards].sort((a,b)=>ovr(b)-ovr(a)).map(cardHTML).join('')}</div>`,
deck:()=>`${head('Deck-Werkstatt','Wähle bis zu fünf Karten für dein Einzelmatch-Deck.','<button id="autoDeck" class="primary">STÄRKSTES DECK</button>')}<div class="panel"><h3>AKTIVES DECK · ${db.deck.length}/5</h3><div class="deck-slots">${Array.from({length:5},(_,i)=>db.deck[i]?cardHTML(db.cards.find(c=>c.uid===db.deck[i])):`<div class="slot">SLOT ${i+1}</div>`).join('')}</div></div><h3>Sammlung wählen</h3><div class="card-grid">${db.cards.map(c=>cardHTML(c,true)).join('')}</div>`,
play:()=>{const deck=db.deck.map(id=>db.cards.find(c=>c.uid===id)).filter(Boolean);const playable=deck.length?deck:db.cards.slice(0,5),own=playable[Math.floor(Math.random()*playable.length)],enemy=CW_DATA.cards[20+Math.floor(Math.random()*20)];return `${head('Match-Demo',`Runde ${matchState.round+1}/3 · Kategorie wird zufällig gewählt`)}<div class="match-arena"><div class="match-card">${cardHTML(own)}</div><div class="versus"><div class="score">${matchState.own} : ${matchState.enemy}</div><strong>VS</strong><button class="primary" id="fightBtn">KARTE WÄHLEN</button></div><div class="match-card">${cardHTML(enemy)}</div></div><div id="matchLog" class="panel match-log">Wähle deine Karte für die nächste Runde.</div><div id="matchResult" class="panel hidden" style="text-align:center"></div>`},
draft:()=>`${head('Draft Board',`${db.picks} Picks verfügbar · Finde die seltene Reset-Karte`)}<div class="draft">${db.draft.map((v,i)=>`<button class="draft-card ${v?'revealed':''}" data-draft="${i}" ${v?'disabled':''}>${v?'✓':'CW'}</button>`).join('')}</div>`,
packs:()=>`${head('Pack Store','Alle Käufe nutzen ausschließlich virtuelle Spielwährung.')}<div class="packs">${CW_DATA.packs.map(p=>`<article class="pack"><div class="pack-art">CW<br>SC</div><h3>${p.name}</h3><p class="muted">${p.desc}</p><button class="primary pack-open" data-pack="${p.id}">${p.price?p.price+' ⬡':'GRATIS'} · ÖFFNEN</button></article>`).join('')}</div>`,
training:()=>`${head('Training','Verbessere eine Karte durch Trainingspunkte.')}<div class="panel"><p class="muted">Wähle eine Karte. Training kostet 200 Credits und erhöht Level sowie alle Werte.</p></div><div class="card-grid">${db.cards.slice(0,12).map(c=>cardHTML(c,true)).join('')}</div>`,
fusion:()=>`${head('Fusion Lab','Verschmelze fünf Karten zu einer stärkeren Belohnung.')}<div class="panel"><h3>GENESIS-FUSION</h3><p class="muted">Rezept: 5 beliebige Karten → 1 Karte einer höheren Seltenheit</p><p>Inventar: <b>${db.cards.length} Karten</b></p><button class="primary" id="fusionBtn" ${db.cards.length<5?'disabled':''}>FUSION STARTEN</button></div>${[['Common Ascension','5 × Gewöhnlich','Ungewöhnlich'],['Rare Circuit','5 × Ungewöhnlich','Selten'],['Epic Forge','5 × Selten','Episch'],['Tag Bond','2 passende Wrestler','Tag Team'],['Faction Core','4 Fraktionsmitglieder','Fraktionskarte']].map(x=>`<div class="list-row"><span><b>${x[0]}</b><br>${x[1]}</span><span class="badge">${x[2]}</span></div>`).join('')}`,
missions:()=>`${head('Missionen','Schließe Aufgaben ab und sichere dir Belohnungen.')}<div class="panel">${db.missions.map((m,i)=>`<div class="list-row"><span><b>${m.name}</b><br><small>${m.progress}/${m.target}</small></span>${m.done?'<button class="primary claim" data-mission="'+i+'">ABHOLEN</button>':'<div class="progress" style="width:150px"><i style="width:'+Math.min(100,m.progress/m.target*100)+'%"></i></div>'}</div>`).join('')}</div>`,
profile:()=>`${head('Spielerprofil','Deine Karriere in der Global Comic Wrestling Federation.')}<div class="panel" style="display:flex;gap:22px;align-items:center"><div class="avatar" style="width:80px;height:80px;font-size:28px">${user.username[0]}</div><div><p class="eyebrow">${user.role}</p><h2 style="margin:4px 0">${user.username}</h2><p class="muted">Mitglied seit ${user.joined} · Liga: Gold</p></div>${['Owner','Administrator'].includes(user.role)?'<button class="primary" style="margin-left:auto" data-page="admin">⚙ ADMIN-CENTER</button>':''}</div><div class="stats-grid"><div class="stat"><strong>LVL ${user.level}</strong><span>SPIELERLEVEL</span></div><div class="stat"><strong>${user.wins}</strong><span>SIEGE</span></div><div class="stat"><strong>${db.cards.length}</strong><span>KARTEN</span></div><div class="stat"><strong>43%</strong><span>SAMMLUNG</span></div></div><div class="panel"><h3>PROFIL BEARBEITEN</h3><label>Benutzername<input id="profileName" class="field" value="${user.username}"></label><button id="saveProfile" class="primary" style="margin-top:12px">SPEICHERN</button></div>`,
settings:()=>`${head('Einstellungen','Alle Änderungen werden lokal gespeichert.')}<div class="panel"><h3>ANZEIGE & GAMEPLAY</h3>${[['dark','Dunkelmodus'],['animations','Animationen'],['effects','Erweiterte Effekte'],['tips','Tooltips'],['autoDeck','Automatische Deckauswahl'],['private','Privates Profil']].map(x=>`<div class="setting-row"><label>${x[1]}</label><button class="toggle ${db.settings[x[0]]?'on':''}" data-setting="${x[0]}"></button></div>`).join('')}<div class="setting-row"><label>Schriftgröße · ${db.settings.fontSize}%</label><input id="fontSize" type="range" min="85" max="120" value="${db.settings.fontSize}"></div><div class="setting-row"><label>Matchgeschwindigkeit</label><select id="matchSpeed" class="field" style="width:150px"><option>Langsam</option><option>Normal</option><option>Schnell</option></select></div></div><div class="panel"><h3>AUDIO</h3>${[['music','Musik'],['sound','Soundeffekte'],['muted','Stummschaltung']].map(x=>`<div class="setting-row"><label>${x[1]}</label><button class="toggle ${db.settings[x[0]]?'on':''}" data-setting="${x[0]}"></button></div>`).join('')}<div class="setting-row"><label>Gesamtlautstärke · ${db.settings.volume}%</label><input id="volume" type="range" min="0" max="100" value="${db.settings.volume}"></div><div class="setting-row"><label>Sprache</label><select id="language" class="field" style="width:150px"><option>Deutsch</option><option>English</option></select></div></div><div class="panel"><h3>KONTO</h3><button id="changePass" class="demo-btn">PASSWORT ÄNDERN</button><button id="logoutSettings" class="demo-btn">ABMELDEN</button><button id="deleteAccount" class="demo-btn" style="color:#ff6576">ACCOUNT LÖSCHEN</button></div>`,
suggestions:()=>`${head('Vorschläge','Deine Ideen helfen, die GCWF weiterzuentwickeln.')}<div class="panel"><h3>NEUEN VORSCHLAG EINREICHEN</h3><select id="suggestType" class="field"><option>Wrestler</option><option>Kartenidee</option><option>Matchtyp</option><option>Event</option><option>Fehlerbericht</option><option>Allgemeine Verbesserung</option></select><textarea id="suggestText" class="field" rows="5" placeholder="Beschreibe deine Idee …"></textarea><button id="submitSuggestion" class="primary" style="margin-top:12px">EINREICHEN</button></div>${db.suggestions.map(s=>`<div class="list-row"><span><b>${s.type}</b><br>${s.text}</span><span class="badge">${s.status}</span></div>`).join('')}`,
admin:()=>{if(!['Owner','Administrator'].includes(user.role))return pages.home();const tabs=['dashboard','users','wrestlers','cards','packs','content','suggestions','logs'];return `${head('Admin-Center','Rollenbasierte Verwaltung · Änderungen werden protokolliert.')}<div class="tabbar">${tabs.map(t=>`<button data-admin="${t}" class="${adminTab===t?'active':''}">${({dashboard:'Dashboard',users:'Benutzer',wrestlers:'Wrestler',cards:'Karten',packs:'Packs',content:'Inhalte',suggestions:'Vorschläge',logs:'Protokoll'})[t]}</button>`).join('')}</div>${adminContent()}`},
dev:()=>`${head('In Entwicklung','Dieses modulare System folgt in einem künftigen Update.')}<div class="panel"><span class="in-dev">IN ENTWICKLUNG</span><h3 style="margin-top:15px">Bald verfügbar</h3><p class="muted">Die Navigation bleibt bewusst funktionsfähig und führt nicht auf eine leere Seite.</p></div>`};
function adminContent(){if(adminTab==='dashboard')return `<div class="admin-grid">${[['Benutzer',128],['Aktive Benutzer',45],['Gesperrt',3],['Wrestler',40],['Karten',75],['Packs',6],['Aktive Events',1],['Offene Vorschläge',18]].map(x=>`<div class="stat"><strong>${x[1]}</strong><span>${x[0].toUpperCase()}</span></div>`).join('')}</div><div class="panel"><h3>PROJEKTFORTSCHRITT · 0.1 UI PROTOTYPE</h3><div class="progress"><i style="width:20%"></i></div><p class="muted">20 % · UI, Navigation und lokale Demo-Systeme aktiv</p></div><div class="panel"><h3>AKTIVITÄT · LETZTE 7 TAGE</h3><div style="display:flex;align-items:end;gap:12px;height:110px">${[42,68,55,88,72,96,80].map((n,i)=>`<i style="height:${n}%;flex:1;background:linear-gradient(var(--cyan),#27446c);border-radius:5px 5px 0 0" title="Tag ${i+1}"></i>`).join('')}</div></div>`;
if(adminTab==='users')return `<div class="panel"><table><tr><th>BENUTZER</th><th>ROLLE</th><th>STATUS</th><th>AKTION</th></tr>${db.users.map(u=>`<tr><td>${u.username}</td><td><select class="field role-change" data-user="${u.id}">${['Owner','Administrator','Moderator','Tester','Premium','Benutzer','Gesperrt'].map(r=>`<option ${u.role===r?'selected':''}>${r}</option>`).join('')}</select></td><td><span class="badge">AKTIV</span></td><td><button class="demo-btn grant" data-user="${u.id}">+1.000 CREDITS</button></td></tr>`).join('')}</table></div>`;
if(adminTab==='wrestlers')return `<div class="panel"><button class="primary add-wrestler">+ WRESTLER ERSTELLEN</button><table><tr><th>RINGNAME</th><th>DIVISION</th><th>STIL</th><th>STATUS</th></tr>${CW_DATA.wrestlers.slice(0,12).map(w=>`<tr><td>${w.ringName}</td><td>${w.gender}</td><td>${w.style}</td><td><span class="badge">${w.status}</span></td></tr>`).join('')}</table></div>`;
if(adminTab==='cards')return `<div class="panel"><button class="primary admin-add-card">+ KARTE ERSTELLEN</button><p>${CW_DATA.cards.length} Basiskarten · ${db.cards.length} Karten im aktiven Inventar</p></div>`;
if(adminTab==='packs')return `<div class="panel">${CW_DATA.packs.map(p=>`<div class="list-row"><span><b>${p.name}</b><br>${p.desc}</span><button class="demo-btn" style="width:auto">BEARBEITEN</button></div>`).join('')}</div>`;
if(adminTab==='content')return `<div class="panel"><h3>SPIELINHALTE</h3><label>Spielname<input id="gameName" class="field" value="${db.gameName}"></label><label>Version<input id="gameVersion" class="field" value="${db.version}"></label><button id="saveContent" class="primary" style="margin-top:15px">ÄNDERUNGEN SPEICHERN</button></div>`;
if(adminTab==='suggestions')return `<div class="panel">${db.suggestions.length?db.suggestions.map((s,i)=>`<div class="list-row"><span><b>${s.type}</b><br>${s.text}</span><select class="field suggestion-status" data-index="${i}" style="width:150px">${['eingereicht','in Prüfung','angenommen','abgelehnt','umgesetzt'].map(x=>`<option ${s.status===x?'selected':''}>${x}</option>`).join('')}</select></div>`).join(''):'<p class="muted">Noch keine Vorschläge eingereicht.</p>'}</div>`;
return `<div class="panel"><table><tr><th>ZEIT</th><th>ADMIN</th><th>AKTION</th></tr>${db.logs.slice().reverse().map(l=>`<tr><td>${l.time}</td><td>${l.admin}</td><td>${l.action}</td></tr>`).join('')}</table>${db.logs.length?'':'<p class="muted">Noch keine Admin-Aktionen.</p>'}</div>`}
function log(action){db.logs.push({time:new Date().toLocaleString('de-DE'),admin:user.username,action});save()}
function bindPage(){bindNav();$('#logoutBtn').onclick=()=>{localStorage.removeItem(SESSION);location.reload()};$('#modalClose').onclick=()=>$('#modal').classList.add('hidden');$('#collapseNav').onclick=()=>document.documentElement.classList.toggle('nav-collapsed');$('#notifyBtn').onclick=()=>openNotifications();$('#messageBtn').onclick=()=>openMessages();$('#mobileMore').onclick=()=>showModal(`<h2>Alle Bereiche</h2><div class="quick-grid">${CW_DATA.nav.slice(3).map(n=>`<button class="tile" data-page="${n[0]}"><i>${n[2]}</i><b>${n[1]}</b></button>`).join('')}</div>`,()=>bindNav());
  if(page==='cards'){const bindCards=()=>$$('#collection .game-card').forEach(el=>el.onclick=()=>openCardDetail(db.cards.find(c=>(c.uid||c.id)===el.dataset.card)));const update=()=>{let a=db.cards.filter(c=>c.name.toLowerCase().includes($('#cardSearch').value.toLowerCase())&&($('#rarityFilter').value===''||c.rarity===$('#rarityFilter').value));a.sort($('#cardSort').value==='name'?(x,y)=>x.name.localeCompare(y.name):$('#cardSort').value==='level'?(x,y)=>y.level-x.level:(x,y)=>ovr(y)-ovr(x));$('#collection').innerHTML=a.map(cardHTML).join('')||'<p class="muted">Keine Karten gefunden.</p>';bindCards()};$('#cardSearch').oninput=update;$('#rarityFilter').onchange=update;$('#cardSort').onchange=update;bindCards()}
  if(page==='deck'){$('#autoDeck').onclick=()=>{db.deck=[...db.cards].sort((a,b)=>ovr(b)-ovr(a)).slice(0,5).map(c=>c.uid);save();toast('Stärkstes Deck gespeichert');render()};$$('.selectable').forEach(el=>el.onclick=()=>{const id=el.dataset.card;if(db.deck.includes(id))db.deck=db.deck.filter(x=>x!==id);else if(db.deck.length<5)db.deck.push(id);else return toast('Das Deck ist bereits voll');save();render()})}
  if(page==='play'&&$('#fightBtn'))$('#fightBtn').onclick=()=>{const statNames=['Stärke','Geschwindigkeit','Technik','Ausdauer','Charisma'],idx=Math.floor(Math.random()*5),vals=$$('.match-card .stats b').map(x=>+x.textContent),a=vals[idx],b=vals[idx+5],win=a>=b;matchState[win?'own':'enemy']++;matchState.round++;$('#matchLog').textContent=`${statNames[idx]}: ${a} zu ${b} – ${win?'Du gewinnst':'Die KI gewinnt'} diese Runde.`;$$('.match-card')[win?0:1].classList.add('winner');if(matchState.round>=3){const victory=matchState.own>matchState.enemy;user[victory?'wins':'losses']++;db.picks+=victory?4:2;user.credits+=victory?300:100;save();$('#matchResult').classList.remove('hidden');$('#matchResult').innerHTML=`<h2>${victory?'MATCH GEWONNEN!':'MATCH VERLOREN'}</h2><p>Endstand ${matchState.own}:${matchState.enemy} · +${victory?300:100} Credits</p><button class="primary" id="matchAgain">NOCH EIN MATCH</button>`;$('#fightBtn').disabled=true;$('#matchAgain').onclick=()=>{matchState={round:0,own:0,enemy:0};render()}}else setTimeout(render,900)};
  if(page==='draft')$$('[data-draft]').forEach(b=>b.onclick=()=>{if(db.picks<=0)return toast('Keine Picks verfügbar');const i=+b.dataset.draft;db.draft[i]=true;db.picks--;const reward=Math.random()<.22?{card:CW_DATA.cards[Math.floor(Math.random()*CW_DATA.cards.length)]}:{credits:100+Math.floor(Math.random()*4)*50};if(reward.card){const c={...reward.card,uid:'uc'+Date.now()};db.cards.push(c);toast(c.name+' gefunden!')}else{user.credits+=reward.credits;toast('+'+reward.credits+' Credits')}save();render()});
  if(page==='packs')$$('.pack-open').forEach(b=>b.onclick=()=>{const p=CW_DATA.packs.find(x=>x.id===b.dataset.pack);if(p.price&&user.credits<p.price)return toast('Nicht genug Credits');user.credits-=p.price;const cards=Array.from({length:p.id==='p0'?1:3},()=>({...CW_DATA.cards[Math.floor(Math.random()*Math.min(CW_DATA.cards.length,(p.max+1)*5))],uid:'uc'+Date.now()+Math.random()}));db.cards.push(...cards);save();showModal(`<p class="eyebrow">PACK REVEAL</p><h2>${p.name}</h2><div class="card-grid">${cards.map(cardHTML).join('')}</div><p>Die Karten wurden deiner Sammlung hinzugefügt.</p>`);});
  if(page==='training')$$('.selectable').forEach(el=>el.onclick=()=>{if(user.credits<200)return toast('Nicht genug Credits');const c=db.cards.find(x=>x.uid===el.dataset.card);user.credits-=200;c.level=Math.min(100,c.level+5);Object.keys(c.stats).forEach(k=>c.stats[k]+=2);save();toast(`${c.name} ist jetzt Level ${c.level}`);render()});
  if(page==='fusion'&&$('#fusionBtn'))$('#fusionBtn').onclick=()=>{const used=db.cards.splice(-5);const tier=Math.min(9,Math.max(...used.map(c=>c.rarity))+1),base=CW_DATA.cards.find(c=>c.rarity===tier)||CW_DATA.cards[tier];db.cards.push({...base,uid:'fusion'+Date.now(),rarity:tier});save();showModal(`<p class="eyebrow">FUSION ABGESCHLOSSEN</p><h2>ENERGIE SYNCHRONISIERT</h2>${cardHTML(db.cards.at(-1))}`)};
  $$('.claim').forEach(b=>b.onclick=()=>{db.missions[+b.dataset.mission].done=false;user.credits+=500;save();toast('+500 Credits abgeholt');render()});
  if($('#saveProfile'))$('#saveProfile').onclick=()=>{const n=$('#profileName').value.trim();if(n.length<3)return toast('Mindestens 3 Zeichen');user.username=n;save();toast('Profil gespeichert');openApp()};
  $$('[data-setting]').forEach(b=>b.onclick=()=>{const k=b.dataset.setting;db.settings[k]=!db.settings[k];save();b.classList.toggle('on');toast('Einstellung gespeichert')});
  if($('#language')){$('#language').value=db.settings.language;$('#language').onchange=e=>{db.settings.language=e.target.value;save();toast('Sprache gespeichert')}}
  if($('#matchSpeed')){$('#matchSpeed').value=db.settings.matchSpeed;$('#matchSpeed').onchange=e=>{db.settings.matchSpeed=e.target.value;save();toast('Matchgeschwindigkeit gespeichert')}}
  if($('#fontSize'))$('#fontSize').onchange=e=>{db.settings.fontSize=+e.target.value;document.documentElement.style.fontSize=e.target.value+'%';save();toast('Schriftgröße gespeichert')};if($('#volume'))$('#volume').onchange=e=>{db.settings.volume=+e.target.value;save();toast('Lautstärke gespeichert')};if($('#logoutSettings'))$('#logoutSettings').onclick=$('#logoutBtn').onclick;
  if($('#changePass'))$('#changePass').onclick=()=>showModal('<h2>Passwort ändern</h2><input id="newPass" class="field" type="password" minlength="6" placeholder="Neues Passwort"><button id="savePass" class="primary" style="margin-top:12px">SPEICHERN</button>',()=>{$('#savePass').onclick=()=>{if($('#newPass').value.length<6)return toast('Mindestens 6 Zeichen');user.password=$('#newPass').value;save();$('#modal').classList.add('hidden');toast('Passwort geändert')}});
  if($('#deleteAccount'))$('#deleteAccount').onclick=()=>{if(confirm('Account und lokale Spieldaten wirklich löschen?')){db.users=db.users.filter(u=>u.id!==user.id);save();localStorage.removeItem(SESSION);location.reload()}};
  if($('#submitSuggestion'))$('#submitSuggestion').onclick=()=>{const text=$('#suggestText').value.trim();if(text.length<10)return toast('Bitte genauer beschreiben');db.suggestions.push({type:$('#suggestType').value,text,status:'eingereicht'});save();toast('Vorschlag eingereicht');render()};
  $$('[data-admin]').forEach(b=>b.onclick=()=>{adminTab=b.dataset.admin;render()});$$('.role-change').forEach(s=>s.onchange=()=>{const u=db.users.find(x=>x.id===s.dataset.user),old=u.role;u.role=s.value;log(`Rolle ${u.username}: ${old} → ${u.role}`);toast('Rolle aktualisiert')});$$('.grant').forEach(b=>b.onclick=()=>{const u=db.users.find(x=>x.id===b.dataset.user);u.credits+=1000;log(`1.000 Credits an ${u.username} vergeben`);toast('Credits vergeben')});$$('.suggestion-status').forEach(s=>s.onchange=()=>{db.suggestions[+s.dataset.index].status=s.value;log(`Vorschlagsstatus auf „${s.value}“ geändert`);toast('Status gespeichert')});if($('#saveContent'))$('#saveContent').onclick=()=>{db.gameName=$('#gameName').value;db.version=$('#gameVersion').value;log(`Spielinhalte geändert: ${db.gameName}, ${db.version}`);toast('Inhalte gespeichert')};if($('.add-wrestler'))$('.add-wrestler').onclick=()=>showModal('<h2>Wrestler erstellen</h2><p class="muted">Editor-Grundsystem aktiv. Neue Datensätze werden in der Datenbankversion ergänzt.</p><span class="in-dev">ERWEITERTER EDITOR IN ENTWICKLUNG</span>');if($('.admin-add-card'))$('.admin-add-card').onclick=()=>showModal('<h2>Karte erstellen</h2><p class="muted">Basiswerte, Seltenheit und Serie sind modular vorbereitet.</p><span class="in-dev">ERWEITERTER EDITOR IN ENTWICKLUNG</span>')}
function showModal(html,after){$('#modalBody').innerHTML=html;$('#modal').classList.remove('hidden');after?.()}
function openCardDetail(c){const w=CW_DATA.wrestlers.find(x=>x.id===c.wrestlerId),r=rarity(c);showModal(`<div style="display:grid;grid-template-columns:minmax(190px,280px) 1fr;gap:24px"><div>${cardHTML(c)}</div><div><p class="eyebrow">${r[0]} · ${c.series}</p><h2>${c.name}</h2><p>Level ${c.level} · ${c.stars} Sterne · OVR ${ovr(c)}</p><p class="muted">${w.ringName} kämpft mit Präzision und explosiver Energie für die ${w.faction}.</p><div class="list-row"><span>Finisher</span><b>${w.finisher}</b></div><div class="list-row"><span>Signature</span><b>${w.signature}</b></div><div class="list-row"><span>Stil</span><b>${w.style}</b></div><div class="list-row"><span>Status</span><b>${w.status}</b></div><button id="detailTrain" class="primary">TRAINIEREN</button><button id="detailDeck" class="demo-btn">ZUM DECK</button><button id="detailFav" class="demo-btn">${c.favorite?'★ FAVORIT':'☆ FAVORISIEREN'}</button></div></div>`,()=>{$('#detailTrain').onclick=()=>{page='training';$('#modal').classList.add('hidden');render()};$('#detailDeck').onclick=()=>{if(!db.deck.includes(c.uid)&&db.deck.length<5)db.deck.push(c.uid);save();toast('Karte zum Deck hinzugefügt')};$('#detailFav').onclick=()=>{c.favorite=!c.favorite;save();toast(c.favorite?'Als Favorit markiert':'Favorit entfernt');$('#modal').classList.add('hidden')}})}
function closeDrawer(){$('.panel-drawer')?.remove()}
function openNotifications(){closeDrawer();const d=document.createElement('aside');d.className='panel-drawer';d.innerHTML=`<button class="close">×</button><p class="eyebrow">OVERLAY</p><h2>Benachrichtigungen</h2><button id="readAll" class="text-btn">ALLE ALS GELESEN MARKIEREN</button>${db.notifications.map((n,i)=>`<div class="drawer-item ${n.read?'':'unread'}" data-note="${i}"><b>${n.title}</b><small>${n.date} · Anklicken zum Lesen</small></div>`).join('')}`;document.body.append(d);d.querySelector('.close').onclick=closeDrawer;d.querySelector('#readAll').onclick=()=>{db.notifications.forEach(n=>n.read=true);save();openNotifications()};d.querySelectorAll('[data-note]').forEach(x=>x.onclick=()=>{const i=+x.dataset.note;db.notifications[i].read=true;save();x.classList.remove('unread');toast('Als gelesen markiert')});$('#notifyCount').textContent=db.notifications.filter(n=>!n.read).length}
function openMessages(){closeDrawer();const d=document.createElement('aside');d.className='panel-drawer';d.innerHTML=`<button class="close">×</button><p class="eyebrow">POSTEINGANG</p><h2>Nachrichten</h2>${db.messages.map((m,i)=>`<div class="drawer-item ${m.read?'':'unread'}" data-msg="${i}"><b>${m.from} · ${m.subject}</b><small>${m.text.slice(0,62)}… · ${m.date}</small></div>`).join('')}`;document.body.append(d);d.querySelector('.close').onclick=closeDrawer;d.querySelectorAll('[data-msg]').forEach(x=>x.onclick=()=>{const m=db.messages[+x.dataset.msg];m.read=true;save();showModal(`<p class="eyebrow">${m.from} · ${m.date}</p><h2>${m.subject}</h2><p>${m.text}</p>`);closeDrawer()})}
boot();
